# Generated by Django 4.0.6 on 2022-12-01 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('code', models.TextField()),
                ('difficulty', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=200)),
                ('lang', models.CharField(default='C++', max_length=50)),
                ('sub_date', models.DateTimeField(verbose_name='date published')),
                ('sub_code', models.TextField(default='SOME STRING')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.problem')),
            ],
        ),
    ]
