# Generated by Django 4.0.6 on 2022-12-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='lang',
            field=models.CharField(default='Java', max_length=50),
        ),
    ]
