# Generated by Django 4.0.6 on 2022-12-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_solution_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='sub_code',
            field=models.TextField(default='Sytstem.out.pringln("hello_world")'),
        ),
    ]
