# Generated by Django 4.1.3 on 2022-12-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_solution_sub_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='sub_code',
            field=models.TextField(default='Sytstem.out.println("hello_world")'),
        ),
    ]
